# Autogenerated wrapper script for zbc2014_jll for aarch64-apple-darwin
export libzbc2014

JLLWrappers.@generate_wrapper_header("zbc2014")
JLLWrappers.@declare_library_product(libzbc2014, "@rpath/libzbc2014.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libzbc2014,
        "lib/libzbc2014.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
